server:
  port: 8082
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: mailtestcjh@gmail.com
    password: xohvhfpztqxdzaqo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/WBR?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: root
    password: 
mybatis:
  type-aliases-package: com.project.demo.vo
custom:
  siteName: WBR
  siteMainUri: http://localhost:8082
  emailFrom: no-reply@localhost
  emailFromName: WBR